version: "3"

tasks:
  start-docker:
    desc: Setups and starts the docker environment
    cmds:
      - docker compose -p directus_imonizer_dev up

  test-docker:
    desc: Setups and starts the docker test environment
    cmds:
      - docker compose -f docker-compose.test.yml -p directus_imonizer_test up --build
